export const REQUEST_REGISTER_AGENT_SUCCESS ='REQUEST_REGISTER_AGENT_SUCCESS'
export const REQUEST_AGENTS_START = 'REQUEST_AGENTS_START';
export const REQUEST_AGENTS_SUCCESS = 'REQUEST_AGENTS_SUCCESS';
export const REQUEST_AGENTS_ERROR = 'REQUEST_AGENTS_ERROR';
export const AGENT_START = 'AGENT_START';
export const AGENT_SUCCESS = 'AGENT_SUCCESS';
export const AGENT_ERROR = 'AGENT_ERROR';
export const SEARCH_AGENT_START = 'SEARCH_AGENT_START';
export const SEARCH_AGENT_SUCCESS = 'SEARCH_AGENT_SUCCESS';
export const SEARCH_AGENT_ERROR = 'SEARCH_AGENT_ERROR';
export const CHANGE_ACTIVE_AGENT_START = 'CHANGE_ACTIVE_AGENT_START';
export const CHANGE_ACTIVE_AGENT_SUCCESS = 'CHANGE_ACTIVE_AGENT_SUCCESS';
export const CHANGE_ACTIVE_AGENT_ERROR = 'CHANGE_ACTIVE_AGENT_ERROR';
export const AGENT_SCHEDULE_START = 'AGENT_SCHEDULE_START';
export const AGENT_SCHEDULE_SUCCESS = 'AGENT_SCHEDULE_SUCCESS';
export const AGENT_SCHEDULE_ERROR = 'AGENT_SCHEDULE_ERROR';
export const START = 'START';
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const LOC_SUCCESS = 'LOC_SUCCESS';
export const EDITED_SUCCESS = 'EDITED_SUCCESS';


