export const AUTH_GET_USER_FROM_TOKEN_SUCCESS = "AUTH_GET_USER_FROM_TOKEN_SUCCESS";
export const AUTH_GET_USER_FROM_TOKEN_ERROR = "AUTH_GET_USER_FROM_TOKEN_ERROR";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const START = "START";
