export const REQ_MIN_MAX_PERCENT_SERVICE_PRICE_LIST = 'REQ_MIN_MAX_PERCENT_SERVICE_PRICE_LIST';
export const REQ_SERVICE_PRICE_LIST = 'REQ_SERVICE_PRICE_LIST';
export const REQ_ERROR = 'REQ_ERROR';
export const START_SERVICE_PRICE = 'START_SERVICE_PRICE';
export const REQ_SUCCESS_SERVICE_PRICE = 'REQ_SUCCESS_SERVICE_PRICE';
export const REQ_GET_SERVICE_PRICE_BY_STATE_LIST_SUCCESS = 'REQ_GET_SERVICE_PRICE_BY_STATE_LIST_SUCCESS';
export const REQ_GET_SERVICE_PRICE_BY_COUNTY_LIST_SUCCESS = 'REQ_GET_SERVICE_PRICE_BY_COUNTY_LIST_SUCCESS';
export const REQ_GET_SERVICE_PRICE_BY_ZIP_CODE_LIST_SUCCESS = 'REQ_GET_SERVICE_PRICE_BY_ZIP_CODE_LIST_SUCCESS';