package uz.pdp.appg4duonotaryserver.entity.enums;

public enum OrderStatus {
    DRAFT,    //QORALAMA,
    NEW,   // ZAKAZ KELDI XALI NAVBATI KELGANI YUQ
    IN_PROGRESS, // ZAKAZ ISHLANYAPDI
    COMPLETED,  // ZAKAS BAJARILDI LEKIN FEEDBEK BERILMADI
    CLOSED,  // ZAKAS TUGATILDI
    REJECTED, // ZAKAZ ROLE_ADMIN TOMONDDAN RAD ETILDI
    CANCELLED  // ZAKAZ CLIENT TOMONDDAN RAD ETILDI
}
